### ISSUE TITLE
IMU -> Position Sensor Calibration

### ISSUE THREAD

**Issue by rikba** [ethz-asl/oomact#48]
Hi

Can you use this framework to obtain the fixed translation of a position sensor with respect to (w.r.t.) an IMU, e.g., IMU to GPS or IMU to Leica? I could only find an example for a [position sensor w.r.t. pose sensor](https://github.com/ethz-asl/oomact/blob/master/oomact_ros_examples/cfg/euroc_MH.info).

Thanks!

**Comment by HannesSommer** [comment]
Yes, it is clearly within the scope. There is even a development branch (https://github.com/ethz-asl/oomact/pull/37). However, this implementation isn't well tested and might still be buggy. If you like to try it I would be interested in helping to use it.

**Comment by rikba** [comment]
Awesome! Will try!
